//sidebarMenu
export const sidebarMenu=[{
  url:'/',
  title:'主页',
  leftIcon:'home',
  rightIcon:'angle-right',
  open:''
},{
  url:'javascript:;',
  title:'测试页面',
  leftIcon:'apple',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/test/test1',
    icon:'arrow-right',
    title:'demo1'
  },{
    url:'/test/test2',
    icon:'arrow-right',
    title:'deno2'
  },{
    url:'/test/dataUI',
    icon:'arrow-right',
    title:'数据可视化管理界面',
    subMenu:[{
      url:'/test/dataUI',
      icon:'arrow-right',
      title:'deno2111111'
    }],
  },{
    url:'/test/test3',
    icon:'arrow-right',
    title:'demo3'
  },{
    url:'/test/test4',
    icon:'arrow-right',
    title:'demo4'
  },{
    url:'/test/test5',
    icon:'arrow-right',
    title:'demo5'
  }]
},{
  url:'javascript:;',
  title:'功能',
  leftIcon:'cogs',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/function/function1',
    icon:'arrow-right',
    title:'功能1'
  },{
    url:'/function/function2',
    icon:'arrow-right',
    title:'功能2'
  },{
    url:'/function/function3',
    icon:'arrow-right',
    title:'功能3'
  }]
},{
  url:'javascript:;',
  title:'UI设计',
  leftIcon:'picture-o',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/ui/ui1',
    icon:'arrow-right',
    title:'UI设计1'
  },{
    url:'/ui/ui2',
    icon:'arrow-right',
    title:'UI设计2'
  },{
    url:'/ui/ui3',
    icon:'arrow-right',
    title:'UI设计3'
  }]
},{
  url:'javascript:;',
  title:'常用插件',
  leftIcon:'gavel',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/plugins/plugin1',
    icon:'arrow-right',
    title:'常用插件1'
  },{
    url:'/plugins/plugin2',
    icon:'arrow-right',
    title:'常用插件2'
  },{
    url:'/plugins/plugin3',
    icon:'arrow-right',
    title:'常用插件3'
  },{
    url:'/plugins/plugin4',
    icon:'arrow-right',
    title:'常用插件4'
  }]
},{
  url:'javascript:;',
  title:'表格',
  leftIcon:'table',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/tables/yTables',
    icon:'arrow-right',
    title:'yTables'
  },{
    url:'/tables/datatables',
    icon:'arrow-right',
    title:'bsTables'
  },{
    url:'/tables/bstables',
    icon:'arrow-right',
    title:'bsTables'
  }]
},{
  url:'javascript:;',
  title:'图表',
  leftIcon:'pie-chart',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/charts/highcharts',
    icon:'arrow-right',
    title:'Highcharts'
  },{
    url:'/charts/echarts',
    icon:'arrow-right',
    title:'Echarts'
  },{
    url:'/charts/Recharts',
    icon:'arrow-right',
    title:'Recharts(D3)'
  },{
    url:'/charts/easypie',
    icon:'arrow-right',
    title:'EasyPie'
  }]
},{
  url:'javascript:;',
  title:'卡片',
  leftIcon:'id-card',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/cards/card2',
    icon:'arrow-right',
    title:'card2'
  },{
    url:'/cards/card1',
    icon:'arrow-right',
    title:'card1',
    subMenu:[{
      url:'/cards/card1/card11',
      title:'card11',
    },{
      url:'/cards/card1/card12',
      title:'card12',
    }]
  },{
    url:'/cards/card3',
    icon:'arrow-right',
    title:'card3'
  }]
},{
  url:'javascript:;',
  title:'表单',
  leftIcon:'th-list',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/form/yform1',
    icon:'arrow-right',
    title:'yform1'
  },{
    url:'/form/yform',
    icon:'arrow-right',
    title:'yform'
  },{
    url:'/form/treedrag',
    icon:'arrow-right',
    title:'TreeDrag'
  }]
},{
  url:'/log',
  title:'日志',
  leftIcon:'github-alt',
  rightIcon:'angle-right',
  open:''
},{
  url:'/fontend',
  title:'前端知识点',
  leftIcon:'html5',
  rightIcon:'angle-right',
  open:''
},{
  url:'/mobx-demo',
  title:'mobx-demo',
  leftIcon:'hourglass-start',
  rightIcon:'angle-right',
  open:''
},{
  url:'javascript:;',
  title:'基础组件',
  leftIcon:'th-list',
  rightIcon:'angle-right',
  open:'',
  subMenu:[{
    url:'/base/layout',
    icon:'arrow-right',
    title:'layout布局'
  },{
    url:'/base/color',
    icon:'arrow-right',
    title:'color颜色'
  },{
    url:'/base/col',
    icon:'arrow-right',
    title:'col栅格'
  },{
    url:'/base/items',
    icon:'arrow-right',
    title:'items列表'
  },{
    url:'/base/list',
    icon:'arrow-right',
    title:'list列表'
  },{
    url:'/base/tabs',
    icon:'arrow-right',
    title:'tabs页签'
  },{
    url:'/base/button',
    icon:'arrow-right',
    title:'button按钮'
  },{
    url:'/base/input',
    icon:'arrow-right',
    title:'input输入框'
  },{
    url:'/base/table',
    icon:'arrow-right',
    title:'表格'
  },{
    url:'/base/form',
    icon:'arrow-right',
    title:'表单'
  },{
    url:'/base/panel',
    icon:'arrow-right',
    title:'面板'
  },{
    url:'/base/echarts',
    icon:'arrow-right',
    title:'图表'
  },{
    url:'/base/tools',
    icon:'arrow-right',
    title:'工具'
  },{
    url:'/base/select',
    icon:'arrow-right',
    title:'单选、多选'
  }]
}];

//notifyList
export const notifyList=[{
  class:'top-left success',
  icon:'check-square-o',
  txt:'更新成功！'
},{
  class:'top-middle warning',
  icon:'exclamation-triangle',
  txt:'数据格式不规范！'
},{
  class:'top-right danger',
  icon:'times-circle',
  txt:'更新出错！'
},{
  class:'bottom-right info',
  icon:'info-circle',
  txt:'请升级版本！'
}];

//dropList
export const dropList={
  searchFlag:true,
  leftList:[{
    name:'theme',
    icon:'cog',
    animate:'up',
    open:'',
    // items:['header','branding','sidebar','active']
    items:['头部','LOGO','侧边栏','选中']
  }],
  rightList:[{
    name:'清缓',
    icon:'trash-o',
    href:'javascript:;',
  },{
    name:'API',
    icon:'book',
    href:'#/api',
  },{
    name:'msg',
    icon:'envelope',
    animate:'left',
    msg:'3',
    open:'',
    items:[{
      pic:'m1',
      h4:'你有一条新信息',
      p:'请注意查收 ',
      icon:'weixin',
    },{
      pic:'m2',
      h4:'你有一条新信息',
      p:'请注意查收 ',
      icon:'weixin',
    },{
      pic:'m3',
      h4:'你有一条新信息',
      p:'请注意查收 ',
      icon:'weixin',
    },{
      pic:'m4',
      h4:'你有一条新信息',
      p:'请注意查收 ',
      icon:'weixin',
    }]
  },{
    name:'tips',
    icon:'bell',
    animate:'up',
    msg:'5',
    open:'',
    items:[{
      pic:'t1',
      h4:'你的系统有更新',
      p:'请升级到最新版本',
      icon:'weixin',
    },{
      pic:'t2',
      h4:'你的系统有更新',
      p:'请升级到最新版本',
      icon:'weixin',
    },{
      pic:'t3',
      h4:'你的系统有更新',
      p:'请升级到最新版本',
      icon:'weixin',
    },{
      pic:'t4',
      h4:'你的系统有更新',
      p:'请升级到最新版本',
      icon:'weixin',
    },{
      pic:'t5',
      h4:'你的系统有更新',
      p:'请升级到最新版本',
      icon:'weixin',
    }]
  },{
    name:'language',
    icon:'html5',
    animate:'down',
    msg:'',
    open:'',
    items:[{
      pic:'中',
      h4:'中文',
      p:'简体',
      icon:'weixin',
    },{
      pic:'英',
      h4:'English',
      p:'en',
      icon:'weixin',
    },{
      pic:'日',
      h4:'Japanese',
      p:'japan',
      icon:'weixin',
    }]
  },{
    name:'profile',
    img:require('../styles/images/usr.jpg'),
    icon:'user',
    animate:'right',
    msg:'4',
    open:'',
    items:[{
      pic:'用',
      h4:'用户信息',
      p:'',
      icon:'weixin',
    },{
      pic:'消',
      h4:'消息',
      p:'',
      icon:'weixin',
    },{
      pic:'设',
      h4:'设置',
      p:'',
      icon:'weixin',
    },{
      pic:'退',
      h4:'退出',
      p:'',
      url:'user/login',
      icon:'weixin',
    }]
  }]
};

//rightbarTabs
export const rightbarTabs=[{
  id:'0',
  name:'tab1',
  icon:'weibo',
  active:''
},{
  id:'1',
  name:'tab2',
  icon:'weixin',
  active:''
},{
  id:'2',
  name:'tab3',
  icon:'qq',
  active:''
},{
  id:'3',
  name:'tab4',
  icon:'apple',
  active:''
}];
//rightbarTabLists
export const rightbarTabLists=[{
  num:'l1',
  pic:'l1',
  h4:'我想起那天夕阳下的奔跑1111111',
  p:'那是我们逝去的青春',
  icon:'hand-o-left'
},{
  num:'l2',
  pic:'l2',
  h4:'我想起那天夕阳下的奔跑',
  p:'那是我们逝去的青春',
  icon:'hand-o-left'
},{
  num:'l3',
  pic:'l3',
  h4:'我想起那天夕阳下的奔跑',
  p:'那是我们逝去的青春',
  icon:'hand-o-left'
},{
  num:'l4',
  pic:'l4',
  h4:'我想起那天夕阳下的奔跑',
  p:'那是我们逝去的青春',
  icon:'hand-o-left'
}];

//tables
export const tableData={
  thead:['ID','青龙','白虎','朱雀','玄武'],
  tbody:[
    [1,'r11','r12','r13','r14'],
    [2,'r21','r22','r23','r24'],
    [3,'r31','r32','r33','r34'],
    [4,'r41','r42','r43','r44'],
    [5,'r51','r52','r53','r54'],
    [6,'r61','r62','r63','r64']
  ]
};

//projectList
export const projectList=[{
  url:'http://localhost:8001/',
  title:'project1',
  icon:'user'
},{
  url:'http://localhost:8002/',
  title:'project2',
  icon:'user'
},{
  url:'http://localhost:8003/',
  title:'project3',
  icon:'user'
},{
  url:'http://localhost:8004/',
  title:'project4',
  icon:'user'
},{
  url:'http://localhost:8005/',
  title:'project5',
  icon:'user'
}];














